# Generated by Django 5.1.6 on 2025-03-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_view',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='receive_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme_preference',
        ),
    ]
