# Generated by Django 5.1.6 on 2025-03-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_remove_userprofile_preferred_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_view',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('list', 'List')], default='daily', max_length=10),
        ),
    ]
